# Datasets N-Dimensionais (astropy.nddata)

De acordo com o site da Astropy¹, a sub-biblioteca astropy.nddata "fornece classes para representar imagens e outros dados em grade", além de possibilitar manipulá-las e muito mais. Veremos a seguir como fazer isso na prática.

### NDData

O objetivo principal do pacote NDData é guardar dados e metadados. Vamos inicialmente criar uma matriz em três dimensões, parecida com a terceira da figura abaixo:

<img src="2-arrays.png" width=50% >

_Imagem disponível em: < https://towardsdatascience.com/numpy-array-cookbook-generating-and-manipulating-arrays-in-python-2195c3988b09 >._

In [1]:
import numpy as np
from astropy.nddata import NDData
array = np.zeros((3, 3, 2))  # Uma matriz tridimensional como a da figura, mas com 0 em cada posição
ndd1 = NDData(array)
print(ndd1)
print(type(ndd1))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
<class 'astropy.nddata.nddata.NDData'>


In [6]:
#Podemos criar também dessa forma:

ndd2 = NDData([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
ndd2

NDData([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

É possível também a matriz no formato array do numpy, seria algo como o "inverso" do que fizemos anteriormente:

In [8]:
print(ndd2.data)
print(type(ndd2.data))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


Mas pense só, se fosse apenas isso, não faria sentido trabalhar com NDData. Então qual a vantagem de trabalhar com NDData e não com as matrizes numpy convencionais?\
A vantagem é que ele suporta propriedades adicionais, como $unit$ (unidade), $mask$, $wcs$ (World Coordinate System), $uncertainty$ (incertezas ou desvio padrão) e $meta$ (atributos adicionais). Vejamos:

In [16]:
from astropy.nddata import StdDevUncertainty

data = np.array([1,2,3,4])
mask = data > 2 #gera uma lista assim: [False False True True], indicando quais pontos são válidos ou não.

unit = 'erg / s'
uncertainty = StdDevUncertainty(np.sqrt(data)) # Calculando o desvio padrão
meta = {'object': 'fictional data.'}

ndd = NDData(data, mask=mask, unit=unit, uncertainty=uncertainty, meta=meta)
ndd

[False False  True  True]
{'object': 'fictional data.'}


NDData([1, 2, 3, 4])

In [17]:
#Para saber mais e entender melhor os parâmetros:
NDData?

Fontes do texto:\
1 - ASTROPY. "N-Dimensional Datasets (astropy.nddata)". Disponível em: < https://docs.astropy.org/en/stable/nddata/index.html >. Acesso em: 22 de novembro de 2020.

Fontes do código:\
ASTROPY. "N-Dimensional Datasets (astropy.nddata)". Disponível em: < https://docs.astropy.org/en/stable/nddata/index.html >. Acesso em: 22 de novembro de 2020.